import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:gita_companion/core/search/concepts.dart';
import 'package:sqlite3/sqlite3.dart';

/// The app must understand questions exactly like the Python reference
/// (content/gita_content/concepts.py); both are checked against the same
/// vectors, generated by content/tools/gen_query_vectors.py.
void main() {
  final vectors =
      jsonDecode(File('../content/tests/query_vectors.json').readAsStringSync()) as Map<String, dynamic>;
  final pack = sqlite3.open('assets/content/gita_content_pack.sqlite', mode: OpenMode.readOnly);
  final index = ConceptIndex.fromDb(pack);
  tearDownAll(pack.close);

  group('normalizeEn', () {
    for (final c in (vectors['normalize_en'] as List).cast<Map<String, dynamic>>()) {
      test(c['text'] as String, () => expect(normalizeEn(c['text'] as String), c['expect']));
    }
  });

  group('teluguStem', () {
    for (final c in (vectors['telugu_stem'] as List).cast<Map<String, dynamic>>()) {
      test(c['term'] as String, () => expect(teluguStem(c['term'] as String), c['expect']));
    }
  });

  group('tokens', () {
    for (final c in (vectors['tokens'] as List).cast<Map<String, dynamic>>()) {
      test(c['text'] as String, () => expect(tokens(c['text'] as String), c['expect']));
    }
  });

  group('match', () {
    for (final c in (vectors['match'] as List).cast<Map<String, dynamic>>()) {
      test(c['query'] as String, () {
        final expected = (c['expect'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(k, (v as num).toDouble()),
        );
        expect(index.match(c['query'] as String), expected);
      });
    }
  });

  test('the pack carries names, definitions and links', () {
    final anger = index.byId['anger']!;
    expect(anger.nameEn, 'Anger');
    expect(anger.nameTe, 'కోపం');
    expect(anger.termSa, 'krodha');
    expect(anger.definition, isNotEmpty);
    expect(anger.verses.keys, containsAll(['2.62', '2.63', '3.37']));
    expect(index.entries.length, greaterThanOrEqualTo(60));
  });
}
