import 'package:drift/drift.dart' show driftRuntimeOptions;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:gita_companion/app/app.dart';
import 'package:gita_companion/app/providers.dart';
import 'package:gita_companion/core/content/sqlite_content_repository.dart';
import 'package:gita_companion/core/search/search_service.dart';
import 'package:gita_companion/core/settings/app_settings.dart';
import 'package:go_router/go_router.dart';

import 'support/audio_fakes.dart';
import 'support/fake_server.dart';
import 'support/pack.dart';
import 'widgets_test.dart' show MemorySettingsRepository;

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;

  late SqliteContentRepository content;
  late SqliteSearchService search;
  setUpAll(() {
    final db = openPackWithSampleAi();
    content = SqliteContentRepository(db);
    search = SqliteSearchService(db, verseExists: content.readingOrder().toSet().contains);
  });

  Future<MemorySettingsRepository> pumpAt(
    WidgetTester tester,
    String route,
    FakeGitaServer server, {
    String builtIn = testServer,
    AppSettings settings = const AppSettings(onboardingDone: true),
  }) async {
    tester.view.physicalSize = const Size(1080, 2400);
    tester.view.devicePixelRatio = 2.5;
    addTearDown(tester.view.reset);
    final store = MemorySettingsRepository()..saved = settings;
    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          contentRepositoryProvider.overrideWithValue(content),
          searchServiceProvider.overrideWithValue(search),
          settingsRepositoryProvider.overrideWithValue(store),
          initialSettingsProvider.overrideWithValue(settings),
          clockProvider.overrideWithValue(() => DateTime(2026, 10, 1)),
          ...TestAudio().overrides,
          ...server.overrides(builtIn: builtIn),
        ],
        child: const GitaApp(),
      ),
    );
    await tester.pumpAndSettle();
    GoRouterHelper(tester.element(find.byType(Scaffold).first)).go(route);
    await tester.pumpAndSettle();
    return store;
  }

  Future<void> work(WidgetTester tester) async {
    for (var i = 0; i < 6; i++) {
      await tester.runAsync(() => Future<void>.delayed(const Duration(milliseconds: 10)));
      await tester.pump(const Duration(milliseconds: 50));
    }
    await tester.pumpAndSettle();
  }

  testWidgets('asking about a verse shows the answer with its checked sources and AI label', (tester) async {
    final server = FakeGitaServer()
      ..answers.add(FakeGitaServer.answer(uncertain: ['How literally to read adhikāra']));
    await pumpAt(tester, '/verse/2.47', server);

    await tester.tap(find.text('Ask about this verse'));
    await tester.pumpAndSettle();
    expect(find.text('About verse 2.47'), findsOneWidget);

    await tester.tap(find.text('Explain with the AI teacher'));
    await work(tester);

    expect(find.textContaining('Act without clinging to results'), findsOneWidget);
    expect(find.textContaining('AI-generated interpretation · llama-test'), findsOneWidget);
    expect(find.text('Sources, checked against the verse text'), findsOneWidget);
    expect(find.text('BG 2.47'), findsOneWidget);
    expect(find.text('The teacher is not certain about:'), findsOneWidget);
    expect(find.textContaining('How literally to read'), findsOneWidget);

    // The conversation was created pinned to the verse, in the default mode.
    final create = server.requests.firstWhere((r) => r.url.path == '/v1/tutor/conversations');
    expect(create.body, contains('"pinned_verse_id":"2.47"'));

    // A source opens the verse.
    await tester.tap(find.text('BG 2.47'));
    await tester.pumpAndSettle();
    expect(find.text('Ask about this verse'), findsOneWidget);
  });

  testWidgets('a missing explanation can be generated by the AI teacher in that mode', (tester) async {
    final server = FakeGitaServer()..answers.add(FakeGitaServer.answer());
    await pumpAt(tester, '/verse/3.19', server);
    await tester.scrollUntilVisible(
      find.text('Explain with the AI teacher'),
      300,
      scrollable: find.byType(Scrollable).last,
    );
    // Clear of the bottom bar.
    await tester.drag(find.byType(Scrollable).last, const Offset(0, -200));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Explain with the AI teacher'));
    await work(tester);
    final explain = server.requests.firstWhere((r) => r.url.path.endsWith('/explain'));
    expect(explain.body, contains('"mode":"simple"'));
    expect(find.text('BG 2.47'), findsOneWidget);
  });

  testWidgets('free questions from Home; validation notices and support note are shown', (tester) async {
    final server = FakeGitaServer()
      ..answers.add(
        FakeGitaServer.answer(
          flags: ['citations_removed', 'unverified_quotes'],
          support: 'Tele-MANAS 14416',
          verses: ['2.47', '2.48'],
        ),
      );
    await pumpAt(tester, '/', server);
    await tester.scrollUntilVisible(
      find.text('Ask the AI teacher'),
      300,
      scrollable: find.byType(Scrollable).first,
    );
    await tester.tap(find.text('Ask the AI teacher'));
    await tester.pumpAndSettle();

    await tester.enterText(find.byType(TextField), 'I feel lost');
    await tester.tap(find.byTooltip('Send'));
    await work(tester);

    expect(find.text('I feel lost'), findsOneWidget);
    expect(find.text('Tele-MANAS 14416'), findsOneWidget);
    expect(find.text('Some references could not be verified and were removed.'), findsOneWidget);
    expect(find.textContaining('Quotations that did not match'), findsOneWidget);
    expect(find.text('BG 2.48'), findsOneWidget);
    final ask = server.requests.firstWhere((r) => r.url.path.endsWith('/messages'));
    expect(ask.body, contains('"mode":"free"'));
  });

  testWidgets('errors are explained, and Try again repeats the question', (tester) async {
    final server = FakeGitaServer()..answers.addAll([(503, 'providers_busy'), FakeGitaServer.answer()]);
    await pumpAt(tester, '/tutor', server);
    await tester.tap(find.text('How can I work without worrying about results?'));
    await work(tester);
    expect(find.text('The AI teacher is busy right now. Please try again in a minute.'), findsOneWidget);
    // The question stays visible while the error is shown.
    expect(find.text('How can I work without worrying about results?'), findsOneWidget);

    await tester.tap(find.text('Try again'));
    await work(tester);
    expect(find.textContaining('Act without clinging'), findsOneWidget);
    expect(find.textContaining('busy right now'), findsNothing);
  });

  testWidgets('no verified answer and quota errors', (tester) async {
    final server = FakeGitaServer()..answers.addAll([(502, 'no_verified_answer'), (429, 'quota_exceeded')]);
    await pumpAt(tester, '/tutor', server);
    await tester.enterText(find.byType(TextField), 'q1');
    await tester.tap(find.byTooltip('Send'));
    await work(tester);
    expect(find.textContaining("couldn't give an answer whose sources could be verified"), findsOneWidget);

    await tester.enterText(find.byType(TextField), 'q2');
    await tester.tap(find.byTooltip('Send'));
    await work(tester);
    expect(find.textContaining("You've used today's questions"), findsOneWidget);
    expect(find.text('Try again'), findsNothing);
  });

  testWidgets('without a server the teacher explains how to set one up', (tester) async {
    final server = FakeGitaServer();
    await pumpAt(tester, '/tutor', server, builtIn: '');
    await tester.enterText(find.byType(TextField), 'Hello');
    await tester.tap(find.byTooltip('Send'));
    await work(tester);
    expect(find.textContaining("isn't set up yet"), findsOneWidget);
    expect(server.requests, isEmpty);
    await tester.tap(find.text('Open settings'));
    await tester.pumpAndSettle();
    expect(find.text('Settings'), findsWidgets);
  });

  testWidgets('Settings: the server address must be HTTPS and is saved', (tester) async {
    final server = FakeGitaServer();
    final store = await pumpAt(tester, '/settings', server, builtIn: '');
    await tester.scrollUntilVisible(
      find.text('Server address'),
      300,
      scrollable: find.byType(Scrollable).first,
    );
    expect(find.text('Not set up'), findsOneWidget);
    await tester.tap(find.text('Server address'));
    await tester.pumpAndSettle();

    await tester.enterText(find.byType(TextField), 'http://gita.example.org');
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle();
    expect(find.text('For your security, the address must start with https://'), findsOneWidget);

    await tester.enterText(find.byType(TextField), 'https://gita.example.org/');
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle();
    expect(store.saved.tutorServer, 'https://gita.example.org');
    expect(find.text('https://gita.example.org'), findsOneWidget);
  });

  testWidgets('past conversations can be reopened and deleted', (tester) async {
    final server = FakeGitaServer()..answers.add(FakeGitaServer.answer());
    await pumpAt(tester, '/tutor', server);
    await tester.enterText(find.byType(TextField), 'What is karma yoga?');
    await tester.tap(find.byTooltip('Send'));
    await work(tester);

    await tester.tap(find.byTooltip('Past conversations'));
    await work(tester);
    expect(find.text('What is karma yoga?'), findsOneWidget);

    await tester.tap(find.text('What is karma yoga?'));
    await work(tester);
    expect(find.textContaining('Act without clinging'), findsOneWidget);
    await tester.pageBack();
    await tester.pumpAndSettle();

    await tester.tap(find.byTooltip('Delete conversation'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Delete'));
    await work(tester);
    expect(find.text('No conversations yet.'), findsOneWidget);
  });
}
