"""initial schema

All tables of the ER design (content, audio, RAG, users, study, progress,
AI tutor, daily practice) plus hand-written Postgres features:
- pgvector extension (embedding_doc.embedding, HNSW cosine index)
- trigger: a verse number must lie within its chapter's verse count
- trigger: updated_at maintained on every UPDATE (mobile sync relies on it)

Revision ID: 0001
Revises:
Create Date: 2026-10-01 06:56:38.646558
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.db import UPDATED_AT_TABLES

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


VERSE_RANGE_FN = """
CREATE FUNCTION verse_within_chapter() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  n smallint;
BEGIN
  SELECT verse_count INTO n FROM chapter WHERE number = NEW.chapter;
  IF NEW.is_canonical AND (NEW.verse < 1 OR NEW.verse > n) THEN
    RAISE EXCEPTION 'verse %.% is outside chapter % (1..%)', NEW.chapter, NEW.verse, NEW.chapter, n
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;
"""

UPDATED_AT_FN = """
CREATE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(VERSE_RANGE_FN)
    op.execute(UPDATED_AT_FN)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("auth_provider", sa.String(length=20), nullable=False),
        sa.Column("external_subject", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "auth_provider IN ('anonymous', 'google', 'email')", name=op.f("ck_app_user_auth_provider")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint(
            "auth_provider", "external_subject", name=op.f("uq_app_user_auth_provider_external_subject")
        ),
    )
    op.create_table(
        "chapter",
        sa.Column("number", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("name_sa", sa.Text(), nullable=False),
        sa.Column("verse_count", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("number BETWEEN 1 AND 18", name=op.f("ck_chapter_number_range")),
        sa.CheckConstraint("verse_count > 0", name=op.f("ck_chapter_verse_count_positive")),
        sa.PrimaryKeyConstraint("number", name=op.f("pk_chapter")),
    )
    op.create_table(
        "concept",
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("term_sa", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept")),
    )
    op.create_table(
        "content_release",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=60), nullable=False),
        sa.Column("verse_count", sa.Integer(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("content_hash", name=op.f("pk_content_release")),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("license", sa.Text(), nullable=False),
        sa.Column("license_note", sa.Text(), server_default="", nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("retrieved_commit", sa.String(length=64), nullable=True),
        sa.Column("tradition", sa.Text(), nullable=True),
        sa.Column("is_ai_generated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('scripture', 'translation', 'commentary', 'transliteration', 'editorial', 'ai', 'dataset', 'recording')",
            name=op.f("ck_source_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_table(
        "speaker",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("line_sa", sa.Text(), nullable=False),
        sa.Column("line_sa_latn", sa.Text(), nullable=False),
        sa.Column("line_sa_telu", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "id IN ('dhritarashtra', 'sanjaya', 'arjuna', 'krishna')", name=op.f("ck_speaker_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speaker")),
    )
    op.create_table(
        "audio_asset",
        sa.Column("audio_hash", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=12), server_default="tts", nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("provider_version", sa.String(length=60), nullable=False),
        sa.Column("voice_id", sa.String(length=120), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("synthesis_rate", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("codec", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("source_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("audio_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_audio_asset_hash_is_sha256")),
        sa.CheckConstraint("origin IN ('tts', 'recording')", name=op.f("ck_audio_asset_origin")),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name=op.f("ck_audio_asset_duration_nonnegative"),
        ),
        sa.CheckConstraint("synthesis_rate > 0", name=op.f("ck_audio_asset_rate_positive")),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_audio_asset_source_id_source")),
        sa.PrimaryKeyConstraint("audio_hash", name=op.f("pk_audio_asset")),
    )
    op.create_table(
        "chapter_text",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chapter", sa.SmallInteger(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=12), server_default="unreviewed", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('name', 'title', 'summary', 'theme')", name=op.f("ck_chapter_text_kind")
        ),
        sa.CheckConstraint(
            "review_status IN ('unreviewed', 'pending', 'reviewed', 'rejected')",
            name=op.f("ck_chapter_text_review_status"),
        ),
        sa.ForeignKeyConstraint(
            ["chapter"], ["chapter.number"], name=op.f("fk_chapter_text_chapter_chapter")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_chapter_text_source_id_source")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter_text")),
        sa.UniqueConstraint(
            "chapter",
            "source_id",
            "kind",
            "language",
            name=op.f("uq_chapter_text_chapter_source_id_kind_language"),
        ),
    )
    op.create_table(
        "concept_text",
        sa.Column("concept_id", sa.String(length=60), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["concept.id"], name=op.f("fk_concept_text_concept_id_concept")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_concept_text_source_id_source")),
        sa.PrimaryKeyConstraint("concept_id", "source_id", "language", name=op.f("pk_concept_text")),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_refresh_token_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_token_token_hash")),
    )
    op.create_index("ix_refresh_token_family", "refresh_token", ["family_id"], unique=False)
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ui_language", sa.String(length=20), server_default="en", nullable=False),
        sa.Column("verse_script", sa.String(length=20), server_default="sa", nullable=False),
        sa.Column("translation_language", sa.String(length=20), server_default="en", nullable=False),
        sa.Column("explanation_language", sa.String(length=20), server_default="en", nullable=False),
        sa.Column("translation_source_id", sa.String(length=80), nullable=True),
        sa.Column("explanation_source_id", sa.String(length=80), nullable=True),
        sa.Column("text_scale", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("theme", sa.String(length=10), server_default="system", nullable=False),
        sa.Column(
            "voice_prefs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("daily_reminder_time", sa.Time(), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("theme IN ('system', 'light', 'dark')", name=op.f("ck_user_settings_theme")),
        sa.CheckConstraint(
            "verse_script IN ('sa', 'sa-Latn', 'sa-Telu')", name=op.f("ck_user_settings_verse_script")
        ),
        sa.CheckConstraint("text_scale BETWEEN 0.75 AND 2.5", name=op.f("ck_user_settings_text_scale_range")),
        sa.ForeignKeyConstraint(
            ["explanation_source_id"],
            ["source.id"],
            name=op.f("fk_user_settings_explanation_source_id_source"),
        ),
        sa.ForeignKeyConstraint(
            ["translation_source_id"],
            ["source.id"],
            name=op.f("fk_user_settings_translation_source_id_source"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_user_settings_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.create_table(
        "verse",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("chapter", sa.SmallInteger(), nullable=False),
        sa.Column("verse", sa.SmallInteger(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column("speaker", sa.String(length=20), nullable=True),
        sa.Column("sanskrit", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("review_status", sa.String(length=12), server_default="unreviewed", nullable=False),
        sa.CheckConstraint("id = chapter::text || '.' || verse::text", name=op.f("ck_verse_id_matches_ref")),
        sa.CheckConstraint(
            "review_status IN ('unreviewed', 'pending', 'reviewed', 'rejected')",
            name=op.f("ck_verse_review_status"),
        ),
        sa.CheckConstraint("is_canonical OR verse = 0", name=op.f("ck_verse_only_verse_zero_noncanonical")),
        sa.CheckConstraint("verse >= 0", name=op.f("ck_verse_verse_nonnegative")),
        sa.ForeignKeyConstraint(["chapter"], ["chapter.number"], name=op.f("fk_verse_chapter_chapter")),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_verse_source_id_source")),
        sa.ForeignKeyConstraint(["speaker"], ["speaker.id"], name=op.f("fk_verse_speaker_speaker")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verse")),
        sa.UniqueConstraint("chapter", "verse", name=op.f("uq_verse_chapter_verse")),
    )
    op.create_table(
        "ai_answer_cache",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hit_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("cache_key ~ '^[0-9a-f]{64}$'", name=op.f("ck_ai_answer_cache_key_is_sha256")),
        sa.CheckConstraint("hit_count >= 0", name=op.f("ck_ai_answer_cache_hits_nonnegative")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_ai_answer_cache_verse_id_verse")),
        sa.PrimaryKeyConstraint("cache_key", name=op.f("pk_ai_answer_cache")),
    )
    op.create_index(op.f("ix_ai_answer_cache_verse_id"), "ai_answer_cache", ["verse_id"], unique=False)
    op.create_table(
        "ai_conversation",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("pinned_verse_id", sa.String(length=8), nullable=True),
        sa.Column("mode", sa.String(length=20), server_default="free", nullable=False),
        sa.Column("language", sa.String(length=20), server_default="en", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mode IN ('simple', 'deep', 'practical', 'story', 'child', 'sanskrit_terms', 'free')",
            name=op.f("ck_ai_conversation_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["pinned_verse_id"], ["verse.id"], name=op.f("fk_ai_conversation_pinned_verse_id_verse")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_ai_conversation_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversation")),
    )
    op.create_index(
        "ix_ai_conversation_user_updated", "ai_conversation", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "audio_manifest",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("chapter", sa.SmallInteger(), nullable=True),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("section", sa.String(length=40), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "scope IN ('verse', 'chapter', 'explanation', 'recitation', 'answer')",
            name=op.f("ck_audio_manifest_scope"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_audio_manifest_version_positive")),
        sa.ForeignKeyConstraint(
            ["chapter"], ["chapter.number"], name=op.f("fk_audio_manifest_chapter_chapter")
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_audio_manifest_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_manifest")),
    )
    op.create_table(
        "bookmark",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("collection", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_bookmark_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_bookmark_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmark")),
    )
    op.create_index(
        "uq_bookmark_user_verse_live",
        "bookmark",
        ["user_id", "verse_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "daily_practice",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("practice_date", sa.Date(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("listened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("understood_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reflected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("journal_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_daily_practice_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_daily_practice_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_practice")),
        sa.UniqueConstraint("user_id", "practice_date", name=op.f("uq_daily_practice_user_id_practice_date")),
    )
    op.create_table(
        "embedding_doc",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("concept_id", sa.String(length=60), nullable=True),
        sa.Column("facet", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', body)", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "facet IN ('sanskrit', 'translation', 'explanation', 'word_meanings', 'concepts', 'commentary', 'concept')",
            name=op.f("ck_embedding_doc_facet"),
        ),
        sa.CheckConstraint(
            "verse_id IS NOT NULL OR concept_id IS NOT NULL", name=op.f("ck_embedding_doc_has_subject")
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["concept.id"], name=op.f("fk_embedding_doc_concept_id_concept")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_embedding_doc_source_id_source")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_embedding_doc_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_doc")),
    )
    op.create_index(
        "ix_embedding_doc_embedding_hnsw",
        "embedding_doc",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_embedding_doc_metadata", "embedding_doc", ["metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_embedding_doc_tsv", "embedding_doc", ["tsv"], unique=False, postgresql_using="gin")
    op.create_index(
        "ix_embedding_doc_verse", "embedding_doc", ["verse_id", "facet", "language"], unique=False
    )
    op.create_table(
        "note",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("chapter", sa.SmallInteger(), nullable=True),
        sa.Column("kind", sa.String(length=12), server_default="note", nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('note', 'question', 'reflection')", name=op.f("ck_note_kind")),
        sa.CheckConstraint("chapter IS NULL OR verse_id IS NULL", name=op.f("ck_note_single_anchor")),
        sa.ForeignKeyConstraint(["chapter"], ["chapter.number"], name=op.f("fk_note_chapter_chapter")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_note_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_note_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note")),
    )
    op.create_index("ix_note_user_updated", "note", ["user_id", "updated_at"], unique=False)
    op.create_table(
        "reading_progress",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chapter", sa.SmallInteger(), nullable=False),
        sa.Column("last_verse_id", sa.String(length=8), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter"], ["chapter.number"], name=op.f("fk_reading_progress_chapter_chapter")
        ),
        sa.ForeignKeyConstraint(
            ["last_verse_id"], ["verse.id"], name=op.f("fk_reading_progress_last_verse_id_verse")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_reading_progress_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "chapter", name=op.f("pk_reading_progress")),
    )
    op.create_table(
        "revision_item",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("card_type", sa.String(length=12), nullable=False),
        sa.Column("state", sa.String(length=12), server_default="new", nullable=False),
        sa.Column("step", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lapses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "card_type IN ('meaning', 'concept', 'application')", name=op.f("ck_revision_item_card_type")
        ),
        sa.CheckConstraint(
            "state IN ('new', 'learning', 'review', 'relearning', 'suspended')",
            name=op.f("ck_revision_item_state"),
        ),
        sa.CheckConstraint(
            "reps >= 0 AND lapses >= 0 AND step >= 0", name=op.f("ck_revision_item_counters_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_revision_item_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_revision_item_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision_item")),
        sa.UniqueConstraint(
            "user_id", "verse_id", "card_type", name=op.f("uq_revision_item_user_id_verse_id_card_type")
        ),
    )
    op.create_index("ix_revision_item_due", "revision_item", ["user_id", "due_at"], unique=False)
    op.create_table(
        "verse_alias",
        sa.Column("edition", sa.String(length=40), nullable=False),
        sa.Column("ref", sa.String(length=8), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_verse_alias_verse_id_verse")),
        sa.PrimaryKeyConstraint("edition", "ref", name=op.f("pk_verse_alias")),
    )
    op.create_table(
        "verse_concept",
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("concept_id", sa.String(length=60), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.Float(), server_default="1.0", nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["concept.id"], name=op.f("fk_verse_concept_concept_id_concept")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_verse_concept_source_id_source")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_verse_concept_verse_id_verse")),
        sa.PrimaryKeyConstraint("verse_id", "concept_id", "source_id", name=op.f("pk_verse_concept")),
    )
    op.create_table(
        "verse_read",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column(
            "first_read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("read_count", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("read_count > 0", name=op.f("ck_verse_read_read_count_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_verse_read_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_verse_read_verse_id_verse")),
        sa.PrimaryKeyConstraint("user_id", "verse_id", name=op.f("pk_verse_read")),
    )
    op.create_table(
        "verse_relation",
        sa.Column("from_verse", sa.String(length=8), nullable=False),
        sa.Column("to_verse", sa.String(length=8), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.CheckConstraint(
            "relation IN ('parallel', 'elaborates', 'contrasts', 'continues')",
            name=op.f("ck_verse_relation_relation"),
        ),
        sa.CheckConstraint("from_verse <> to_verse", name=op.f("ck_verse_relation_not_self")),
        sa.ForeignKeyConstraint(
            ["from_verse"], ["verse.id"], name=op.f("fk_verse_relation_from_verse_verse")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_verse_relation_source_id_source")
        ),
        sa.ForeignKeyConstraint(["to_verse"], ["verse.id"], name=op.f("fk_verse_relation_to_verse_verse")),
        sa.PrimaryKeyConstraint("from_verse", "to_verse", "relation", name=op.f("pk_verse_relation")),
    )
    op.create_table(
        "verse_state",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_understood", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("needs_revision", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_verse_state_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_verse_state_verse_id_verse")),
        sa.PrimaryKeyConstraint("user_id", "verse_id", name=op.f("pk_verse_state")),
    )
    op.create_table(
        "verse_text",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=12), server_default="unreviewed", nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('transliteration', 'literal_translation', 'translation', 'simple', 'deep', 'practical', 'story', 'child', 'sanskrit_terms', 'commentary')",
            name=op.f("ck_verse_text_kind"),
        ),
        sa.CheckConstraint(
            "review_status IN ('unreviewed', 'pending', 'reviewed', 'rejected')",
            name=op.f("ck_verse_text_review_status"),
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_verse_text_source_id_source")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_verse_text_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verse_text")),
        sa.UniqueConstraint(
            "verse_id",
            "source_id",
            "kind",
            "language",
            name=op.f("uq_verse_text_verse_id_source_id_kind_language"),
        ),
    )
    op.create_index("ix_verse_text_lookup", "verse_text", ["verse_id", "kind", "language"], unique=False)
    op.create_table(
        "word_meaning",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("word_sa", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_word_meaning_position_nonnegative")),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_word_meaning_source_id_source")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_word_meaning_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_meaning")),
        sa.UniqueConstraint(
            "verse_id",
            "source_id",
            "language",
            "position",
            name=op.f("uq_word_meaning_verse_id_source_id_language_position"),
        ),
    )
    op.create_table(
        "ai_message",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model_id", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column(
            "uncertain_points", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "role <> 'assistant' OR (model_id IS NOT NULL AND provider IS NOT NULL)",
            name=op.f("ck_ai_message_assistant_has_model"),
        ),
        sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f("ck_ai_message_role")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversation.id"],
            name=op.f("fk_ai_message_conversation_id_ai_conversation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_message")),
    )
    op.create_index(
        "ix_ai_message_conversation", "ai_message", ["conversation_id", "created_at"], unique=False
    )
    op.create_table(
        "audio_chunk",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("manifest_id", sa.String(length=120), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("section", sa.String(length=40), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("audio_hash", sa.String(length=64), nullable=True),
        sa.Column("est_seconds", sa.Float(), nullable=False),
        sa.CheckConstraint("est_seconds > 0", name=op.f("ck_audio_chunk_est_positive")),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_audio_chunk_seq_nonnegative")),
        sa.ForeignKeyConstraint(
            ["audio_hash"], ["audio_asset.audio_hash"], name=op.f("fk_audio_chunk_audio_hash_audio_asset")
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["audio_manifest.id"],
            name=op.f("fk_audio_chunk_manifest_id_audio_manifest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_audio_chunk_verse_id_verse")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_chunk")),
        sa.UniqueConstraint("manifest_id", "seq", name=op.f("uq_audio_chunk_manifest_id_seq")),
    )
    op.create_table(
        "highlight",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("verse_text_id", sa.UUID(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=20), server_default="gold", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset", name=op.f("ck_highlight_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_highlight_user_id_app_user"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_highlight_verse_id_verse")),
        sa.ForeignKeyConstraint(
            ["verse_text_id"], ["verse_text.id"], name=op.f("fk_highlight_verse_text_id_verse_text")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlight")),
    )
    op.create_index("ix_highlight_user_verse", "highlight", ["user_id", "verse_id"], unique=False)
    op.create_table(
        "listening_progress",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("manifest_id", sa.String(length=120), nullable=False),
        sa.Column("manifest_version", sa.Integer(), nullable=False),
        sa.Column("chapter", sa.SmallInteger(), nullable=True),
        sa.Column("verse_id", sa.String(length=8), nullable=True),
        sa.Column("audio_chunk_id", sa.String(length=160), nullable=False),
        sa.Column("position_seconds", sa.Float(), server_default="0", nullable=False),
        sa.Column("speed", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("position_seconds >= 0", name=op.f("ck_listening_progress_position_nonnegative")),
        sa.CheckConstraint(
            "speed IN (0.75, 1.0, 1.25, 1.5, 1.75, 2.0)", name=op.f("ck_listening_progress_speed_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["chapter"], ["chapter.number"], name=op.f("fk_listening_progress_chapter_chapter")
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["audio_manifest.id"],
            name=op.f("fk_listening_progress_manifest_id_audio_manifest"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_listening_progress_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verse_id"], ["verse.id"], name=op.f("fk_listening_progress_verse_id_verse")
        ),
        sa.PrimaryKeyConstraint("user_id", "manifest_id", name=op.f("pk_listening_progress")),
    )
    op.create_table(
        "revision_review",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("elapsed_days", sa.Float(), nullable=True),
        sa.Column("scheduled_days", sa.Float(), nullable=True),
        sa.CheckConstraint("rating BETWEEN 1 AND 4", name=op.f("ck_revision_review_rating_range")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["revision_item.id"],
            name=op.f("fk_revision_review_item_id_revision_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision_review")),
    )
    op.create_index(op.f("ix_revision_review_item_id"), "revision_review", ["item_id"], unique=False)
    op.create_table(
        "ai_citation",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("verse_id", sa.String(length=8), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["ai_message.id"],
            name=op.f("fk_ai_citation_message_id_ai_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], name=op.f("fk_ai_citation_source_id_source")),
        sa.ForeignKeyConstraint(["verse_id"], ["verse.id"], name=op.f("fk_ai_citation_verse_id_verse")),
        sa.PrimaryKeyConstraint("message_id", "verse_id", name=op.f("pk_ai_citation")),
    )
    # ### end Alembic commands ###

    op.execute(
        "CREATE TRIGGER verse_within_chapter BEFORE INSERT OR UPDATE ON verse "
        "FOR EACH ROW EXECUTE FUNCTION verse_within_chapter()"
    )
    for table in UPDATED_AT_TABLES:
        op.execute(
            f"CREATE TRIGGER set_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_citation")
    op.drop_index(op.f("ix_revision_review_item_id"), table_name="revision_review")
    op.drop_table("revision_review")
    op.drop_table("listening_progress")
    op.drop_index("ix_highlight_user_verse", table_name="highlight")
    op.drop_table("highlight")
    op.drop_table("audio_chunk")
    op.drop_index("ix_ai_message_conversation", table_name="ai_message")
    op.drop_table("ai_message")
    op.drop_table("word_meaning")
    op.drop_index("ix_verse_text_lookup", table_name="verse_text")
    op.drop_table("verse_text")
    op.drop_table("verse_state")
    op.drop_table("verse_relation")
    op.drop_table("verse_read")
    op.drop_table("verse_concept")
    op.drop_table("verse_alias")
    op.drop_index("ix_revision_item_due", table_name="revision_item")
    op.drop_table("revision_item")
    op.drop_table("reading_progress")
    op.drop_index("ix_note_user_updated", table_name="note")
    op.drop_table("note")
    op.drop_index("ix_embedding_doc_verse", table_name="embedding_doc")
    op.drop_index("ix_embedding_doc_tsv", table_name="embedding_doc", postgresql_using="gin")
    op.drop_index("ix_embedding_doc_metadata", table_name="embedding_doc", postgresql_using="gin")
    op.drop_index(
        "ix_embedding_doc_embedding_hnsw",
        table_name="embedding_doc",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("embedding_doc")
    op.drop_table("daily_practice")
    op.drop_index(
        "uq_bookmark_user_verse_live", table_name="bookmark", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("bookmark")
    op.drop_table("audio_manifest")
    op.drop_index("ix_ai_conversation_user_updated", table_name="ai_conversation")
    op.drop_table("ai_conversation")
    op.drop_index(op.f("ix_ai_answer_cache_verse_id"), table_name="ai_answer_cache")
    op.drop_table("ai_answer_cache")
    op.drop_table("verse")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_index("ix_refresh_token_family", table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_table("concept_text")
    op.drop_table("chapter_text")
    op.drop_table("audio_asset")
    op.drop_table("speaker")
    op.drop_table("source")
    op.drop_table("content_release")
    op.drop_table("concept")
    op.drop_table("chapter")
    op.drop_table("app_user")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS verse_within_chapter()")
    # The vector extension is left installed: other databases objects may use it.
