"""Regenerate tests/query_vectors.json from the Python reference implementation.

    python tools/gen_query_vectors.py

The app's port (mobile/lib/core/search/concepts.dart) is tested against the
same file, so both must agree. Review the diff before committing: a change
here changes how every query is understood.
"""

import json
from pathlib import Path

from gita_content.concepts import load_concepts, match_concepts, normalize_en, telugu_stem, tokens

OUT = Path(__file__).resolve().parent.parent / "tests" / "query_vectors.json"
TEXTS = [
    "Worries, worried, worrying",
    "I'm anxious about my exam results",
    "attached attachments running stopped",
    "What's the meaning of life?",
    "Lift yourself up!",
    "passes classes boxes watches wishes",
    "happily quickly",
    "studies studied",
    "kindness sadness",
    "it's Krishna's teaching",
    "కోపాన్ని ఎలా నియంత్రించాలి",
    "karmanye vadhikaraste",
    "2.47 and BG 18:66",
    "Sacrifice (yajña) of Pârtha",
    "Kṛṣṇa’s śloka",
]
QUERIES = [
    "I'm anxious about the results of my work",
    "How do I control my anger?",
    "What happens after death?",
    "I feel lazy and procrastinate",
    "కోపాన్ని ఎలా నియంత్రించాలి?",
    "మరణం తర్వాత ఏమవుతుంది?",
    "what is sthitaprajna",
    "Is God partial?",
    "should I quit my job",
    "how do I fix my mind on God",
    "what is karma yoga",
    "Arjuna does not want to fight",
    "నా మనసు చంచలంగా ఉంది",
    "the three gunas",
    "krodha",
    "plain words with no concept",
    "భక్తుని లక్షణాలు",
    "yajña",
    "Kṛṣṇa on bhakti",
]
TELUGU = ["కోపం", "కోపము", "ఫలితాలు", "బాధలు", "చిరాకు", "భయం", "మనసు", "ఆత్మ"]


def main() -> None:
    concepts = load_concepts()
    out = {
        "_comment": "Generated by tools/gen_query_vectors.py. Shared by tests/test_concepts.py and "
        "mobile/test/concepts_test.dart: the app must tokenise, normalise and match queries exactly "
        "like the Python reference.",
        "normalize_en": [{"text": t, "expect": normalize_en(t)} for t in TEXTS],
        "telugu_stem": [{"term": t, "expect": telugu_stem(t)} for t in TELUGU],
        "tokens": [
            {"text": t, "expect": tokens(t)} for t in ["I'm fine—really", "కోపాన్ని ఎలా?", "2.47 karmaṇy-eva"]
        ],
        "match": [{"query": q, "expect": dict(sorted(match_concepts(q, concepts).items()))} for q in QUERIES],
    }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
